version: "3.8"

services:
    pg_database:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: 12345
            POSTGRES_USER: postgres
            POSTGRES_DB: test_db
    backend:
        build:
            context: ../backend/
            dockerfile: dockerfile.dev
        depends_on:
            - pg_database
        image: test/back
        container_name: backend
        ports:
            - "8000:8000"
        restart: unless-stopped